name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    name: Build - Windows
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build shadowJar
        name: Build and create JAR
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/

  build-macos:
    name: Build - macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
        name: Make gradlew executable
      - run: ./gradlew build shadowJar
        name: Build and create JAR
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/
  
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
        name: Make gradlew executable
      - run: ./gradlew build shadowJar
        name: Build and create JAR
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/
